### ISSUE TITLE
Error window for no visible reason

### ISSUE THREAD

**Issue by borodin-devel** [Aldrin-John-Olaer-Manalansan/RA2YR-reMIXer#5]
MIX archive is marked as recoverable for header and LMD. Recommended method is used.
Error window appears during extraction, but extraction is complete and work is done.
Recovered MIX seems to have some files with missing names, some files appear to have zeros in them. 

---------------------------
reMIXer.exe
---------------------------
Invalid memcpy_s parameters:

Destination: 0x771333A
DestinationSize: 46421
Source: 0x639D452
SourceSize: 88712
MaxAllowedSize: 11003657

---------------------------
ОК   
---------------------------

Problematic files are attached in G-Drive.

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
> MIX archive is marked as recoverable for header and LMD. Recommended method is used. Error window appears during extraction, but extraction is complete and work is done. Recovered MIX seems to have some files with missing names, some files appear to have zeros in them.
> 
> ## reMIXer.exe
> Invalid memcpy_s parameters:
> 
> Destination: 0x771333A DestinationSize: 46421 Source: 0x639D452 SourceSize: 88712 MaxAllowedSize: 11003657
> 
> ## ОК
> Problematic files are attached in G-Drive.

I examined that MIX File and gave me some interesting backtrace information:
Sucess Add_File: ID=366E051F OffsetFromBody: 0xA7AD50 Size=392 To_reMIX: RemainingBodySize=11003657
Sucess Add_File: ID=8005B070 OffsetFromBody: 0x0 Size=1872 To_reMIX: RemainingBodySize=11003265
Sucess Add_File: ID=925B86F2 OffsetFromBody: 0x750 Size=1872 To_reMIX: RemainingBodySize=11001393
Sucess Add_File: ID=9845B67A OffsetFromBody: 0xEA0 Size=26504 To_reMIX: RemainingBodySize=10999521
Sucess Add_File: ID=99CD50C2 OffsetFromBody: 0x272E Size=22322 To_reMIX: RemainingBodySize=10973017
Sucess Add_File: ID=9F999465 OffsetFromBody: 0xA7AEE0 Size=13865 To_reMIX: RemainingBodySize=10950695
Sucess Add_File: ID=9FC5417D OffsetFromBody: 0x7630 Size=1872 To_reMIX: RemainingBodySize=10936830
Sucess Add_File: ID=B1EDF14E OffsetFromBody: 0x7D80 Size=2256720 To_reMIX: RemainingBodySize=10934958
Sucess Add_File: ID=B363B263 OffsetFromBody: 0x22ECD0 Size=49188 To_reMIX: RemainingBodySize=8678238
Sucess Add_File: ID=B636CAE2 OffsetFromBody: 0x23AD00 Size=33126 To_reMIX: RemainingBodySize=8629050
Sucess Add_File: ID=DE299E86 OffsetFromBody: 0x242E70 Size=41213 To_reMIX: RemainingBodySize=8595924
Sucess Add_File: ID=E5FBBDF6 OffsetFromBody: 0x24CF70 Size=23349 To_reMIX: RemainingBodySize=8554711
Sucess Add_File: ID=E8DF0937 OffsetFromBody: 0x252AB0 Size=2290353 To_reMIX: RemainingBodySize=8531362
Sucess Add_File: ID=E99E00A7 OffsetFromBody: 0x481D70 Size=2305 To_reMIX: RemainingBodySize=6241009
Sucess Add_File: ID=EFFE79FC OffsetFromBody: 0x482680 Size=21448 To_reMIX: RemainingBodySize=6238704
Sucess Add_File: ID=F4887B6B OffsetFromBody: 0x487A50 Size=413 To_reMIX: RemainingBodySize=6217256
Sucess Add_File: ID=02C0176E OffsetFromBody: 0x487BF0 Size=39729 To_reMIX: RemainingBodySize=6216843
Sucess Add_File: ID=062DC483 OffsetFromBody: 0x491730 Size=898681 To_reMIX: RemainingBodySize=6177114
Sucess Add_File: ID=10B3D5DA OffsetFromBody: 0x56CDB0 Size=298063 To_reMIX: RemainingBodySize=5278433
Sucess Add_File: ID=11B6B299 OffsetFromBody: 0x5B5A00 Size=36 To_reMIX: RemainingBodySize=4980370
Sucess Add_File: ID=11E7B07E OffsetFromBody: 0x5B5A30 Size=41657 To_reMIX: RemainingBodySize=4980334
Sucess Add_File: ID=45365077 OffsetFromBody: 0x5BFCF0 Size=102 To_reMIX: RemainingBodySize=4938677
Sucess Add_File: ID=52FE1053 OffsetFromBody: 0x5BFD60 Size=1150973 To_reMIX: RemainingBodySize=4938575
Sucess Add_File: ID=64C19292 OffsetFromBody: 0x6D8D60 Size=2638295 To_reMIX: RemainingBodySize=3787602
Sucess Add_File: ID=66BF0E67 OffsetFromBody: 0x95CF40 Size=1034718 To_reMIX: RemainingBodySize=1149307


Sucess Add_File: ID=6AB96D6B OffsetFromBody: 0x4DD Size=20661 To_reMIX: RemainingBodySize=114589 <--- Garbage LookupTable Information that causes filesize alignment error


Sucess Add_File: ID=7032B1CC OffsetFromBody: 0xA59920 Size=16319 To_reMIX: RemainingBodySize=93928
Sucess Add_File: ID=7475C6D2 OffsetFromBody: 0xA5D8E0 Size=31188 To_reMIX: RemainingBodySize=77609
Failed Add_File: ID=77CBA44D OffsetFromBody: 0xA652C0 Size=88712 To_reMIX: RemainingBodySize=46421
Created _1_expandmo99.mix from C:\Users\ADMIN\Downloads\Compressed\mixes\mixes\expandmo99.mix


Using Level 3 Mode: The Garbage Information occupied its own file size during the reconstruction process which misaligned the next remaining file entries. Will be fixed on the next update.


This Garbage Information found at the LookupTable must've been Added by a MIX Protector... If you know something about what MIX protector this is, you might as well share it here(app download link would be better) so that I can reverse its techniques even further...

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
This issue is now assumed as Fixed.

Ticket Closed.
